import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';
import { randomUUID } from 'node:crypto';

const root=process.cwd();
const dataDir=join(root,'data');
const templateFile=join(root,'report-template.html');
async function loadLocalEnv(){try{const contents=await readFile(join(root,'.env'),'utf8');for(const line of contents.split(/\r?\n/)){const match=line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);if(!match||process.env[match[1]])continue;let value=match[2];if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);process.env[match[1]]=value;}}catch(error){if(error.code!=='ENOENT')throw error;}}
await loadLocalEnv();
const systemPrompt=`You are Better Said, a neutral conversation companion. You never decide who is right about a political, ethical, or factual disagreement. Analyse communication patterns, not people's character or motives. Apply the same standard to every participant. Use warm plain language. A written transcript cannot reveal tone, history, intent, or body language. For every observation give a practical, non-coercive way forward. Do not diagnose people. If there are threats, severe distress, or safety risks, prioritise de-escalation and appropriate human support.`;
const clusterKeys=['assumptions_biases','judgment_language','misunderstandings','focus_efficiency','status_dominance'];
const clusterSchema={type:'object',additionalProperties:false,required:['count','quote','effect','before','after'],properties:{count:{type:'integer',minimum:0,maximum:8},quote:{type:'string'},effect:{type:'string'},before:{type:'string'},after:{type:'string'}}};
const intensitySchema={type:'object',additionalProperties:false,required:clusterKeys,properties:Object.fromEntries(clusterKeys.map(key=>[key,{type:'integer',minimum:0,maximum:10}]))};
const profileKeys=['person_1','person_2','person_3','person_4'];
const reportSchema={type:'object',additionalProperties:false,required:['participants','participant_labels','tone','overview','clusters','frequency_applicable','frequency_note','sourced_context','closing_note','intensity'],properties:{participants:{type:'string'},participant_labels:{type:'array',minItems:2,maxItems:4,items:{type:'string'}},tone:{type:'string'},overview:{type:'string'},clusters:{type:'object',additionalProperties:false,required:clusterKeys,properties:Object.fromEntries(clusterKeys.map(key=>[key,clusterSchema]))},frequency_applicable:{type:'boolean'},frequency_note:{type:'string'},sourced_context:{type:'array',maxItems:4,items:{type:'object',additionalProperties:false,required:['concept','note','url'],properties:{concept:{type:'string'},note:{type:'string'},url:{type:'string'}}}},closing_note:{type:'string'},intensity:{type:'object',additionalProperties:false,required:profileKeys,properties:Object.fromEntries(profileKeys.map(key=>[key,intensitySchema]))}}};
function outputText(apiResponse){if(apiResponse.output_text)return apiResponse.output_text;return (apiResponse.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('');}
async function openAI(body){if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is missing. Follow SETUP.md, then restart the local server.');const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'OpenAI request failed.');return result;}
function mapLayerIntensities(layer1){const mapped={};layer1.participant_labels.forEach((label,index)=>{mapped[label]=layer1.intensity[profileKeys[index]];});layer1.intensity=mapped;return layer1;}
async function analyze(transcript){const request={model:process.env.OPENAI_MODEL||'gpt-5',store:false,instructions:systemPrompt,input:`Create a complete Better Said conversation analysis for this transcript. The finished result is a polished personal reflection report, with an overview, observed pattern counts, a personal profile, evidence cards, and a closing note.

Identify every distinct speaker who contributes meaningfully, up to four people, in speaking order. Put their exact names in participant_labels and make participants a readable “Name / Name / Name” string. Create one private profile for each listed speaker. If attribution is genuinely unclear, use Person A and Person B, set frequency_applicable false, and explain why.

Use only these five lenses: assumptions_biases (unsupported assumptions, stereotyping, confirmation bias); judgment_language (dismissive, absolute, manipulative, or sharp wording); misunderstandings (different meanings, missed intent, talking past each other); focus_efficiency (repetition, tangents, unclear decision-making); status_dominance (interrupting, pressure, dismissive “yes, but”, unequal space).

Extraction-completeness check before responding: re-scan the transcript for each lens. Do not return an all-clear result merely because the dialogue is short, businesslike, or polite. Flag a pattern only when a direct quote supports it. For every cluster with a positive count, include exactly one short verbatim quote, a specific 1–2 sentence impact, the original wording as before, and one natural micro-shift as after. For a clear cluster, use count 0 and empty strings. Never invent quotes, declare anyone right, diagnose people, compare people, or offer generic advice.

Score each listed speaker only from their own contribution. person_1 corresponds to participant_labels[0], person_2 to [1], person_3 to [2], and person_4 to [3]. Use 0 for unused profiles. Scores: 0 none, 1–3 mild, 4–6 moderate, 7–8 frequent/pointed, 9–10 severe/pervasive. Keep overview and closing_note concrete, charitable, and text-only. Provide sourced_context only for URLs you know are real and credible; otherwise use an empty list. Transcript:\n\n${transcript}`,text:{format:{type:'json_schema',name:'better_said_layer_one',strict:true,schema:reportSchema}}};const raw=await openAI(request);return mapLayerIntensities(JSON.parse(outputText(raw)));}
async function mentor({topic,otherSide,history}){const text=history.map(x=>`${x.role}: ${x.content}`).join('\n');const raw=await openAI({model:process.env.OPENAI_MODEL||'gpt-5',store:false,instructions:systemPrompt+' You are coaching one person before a difficult conversation. Give one short neutral response and one specific mentoring suggestion. Return exactly JSON with reply and mentoring.',input:`Topic: ${topic||'Not specified'}\nOther perspective, as described by the user: ${otherSide||'Not specified'}\n\nConversation so far:\n${text}`,text:{format:{type:'json_schema',name:'mentoring_reply',strict:true,schema:{type:'object',additionalProperties:false,required:['reply','mentoring'],properties:{reply:{type:'string'},mentoring:{type:'string'}}}}}});return JSON.parse(outputText(raw));}
const firstPassAnalyze=analyze;
function needsCompletenessReview(transcript,report){const total=clusterKeys.reduce((sum,key)=>sum+(report.clusters?.[key]?.count||0),0);const hasStrongCue=/\b(always|never|failed|failure|wrong|blame|stupid|useless|no|can't|cannot|but|unfair|ridiculous|obviously)\b/i.test(transcript);return total===0&&hasStrongCue&&transcript.trim().split(/\s+/).length>=80;}
async function reviewAnalysis(transcript){const raw=await openAI({model:process.env.OPENAI_MODEL||'gpt-5',store:false,instructions:systemPrompt+' You are a quality reviewer for a completed conversation analysis. Re-read the transcript for specific, directly supported patterns. Do not treat a respectful tone as proof that no pattern occurred. Flag only evidence you can quote verbatim. It is valid to leave a cluster at zero if it is truly absent, but do not leave every cluster at zero when concrete evidence exists.',input:`Quality-review this speaker-labelled transcript. Return the same complete Better Said Layer 1 JSON schema, including every meaningful participant (up to four) and a private intensity profile for each. Check especially for unsupported assumptions, absolute or dismissive language, talking past each other, repeated/tangential discussion, and dominance or reduced speaking space. For each positive count, include exactly one short verbatim quote and one useful neutral micro-shift. Transcript:\n\n${transcript}`,text:{format:{type:'json_schema',name:'better_said_completeness_review',strict:true,schema:reportSchema}}});return mapLayerIntensities(JSON.parse(outputText(raw)));}
analyze=async function(transcript){const firstPass=await firstPassAnalyze(transcript);return needsCompletenessReview(transcript,firstPass)?reviewAnalysis(transcript):firstPass;};
async function body(req){let text='';for await(const part of req){text+=part;if(text.length>1_500_000)throw new Error('Request is too large.');}return JSON.parse(text||'{}');}
function hasClearSpeakerAttribution(transcript){const speakers=[...transcript.matchAll(/^\s*([^:\n]{1,50}):\s*\S+/gm)].map(match=>match[1].trim()).filter(label=>!/^https?$/i.test(label));return new Set(speakers).size>=2;}
function send(res,status,payload,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(payload):payload);}
function buildPersonalPayload(layer1,viewerLabel){const {participant_labels,intensity,...shared}=layer1;return {...shared,viewer_label:viewerLabel,own_intensity:intensity[viewerLabel]};}
function validatePersonalPayload(payload){if(!payload.viewer_label||!payload.own_intensity||clusterKeys.some(key=>!Number.isInteger(payload.own_intensity[key])))throw new Error('The private report profile is incomplete. Please try again.');if('participant_labels' in payload||'intensity' in payload)throw new Error('Privacy check failed while preparing the report.');}
async function reportDocument(report){const template=await readFile(templateFile,'utf8');const safeJson=JSON.stringify(report).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');const rendered=template.replace(/(<script id="report-data" type="application\/json">\s*)__REPORT_DATA_JSON__(\s*<\/script>)/,(match,start,end)=>`${start}${safeJson}${end}`);if(rendered===template)throw new Error('The report template is missing its report-data section.');return rendered;}
const server=createServer(async(req,res)=>{try{if(req.method==='POST'&&req.url==='/api/analyze'){const {transcript}=await body(req);if(typeof transcript!=='string'||transcript.trim().length<20)return send(res,400,{error:'Please provide a longer transcript.'});if(!hasClearSpeakerAttribution(transcript))return send(res,400,{error:'This looks like a document rather than a conversation. Paste a transcript with at least two speaker labels, for example “Alex: …” and “Sam: …”, so Bettersaid can analyse the exchange fairly.'});await mkdir(join(dataDir,'transcripts'),{recursive:true});const id=`${new Date().toISOString().replace(/[:.]/g,'-')}-${randomUUID().slice(0,8)}`;await writeFile(join(dataDir,'transcripts',`${id}.txt`),transcript,'utf8');const layer1=await analyze(transcript);await mkdir(join(dataDir,'reports'),{recursive:true});await writeFile(join(dataDir,'reports',`${id}.json`),JSON.stringify(layer1,null,2),'utf8');const reports=[];for(const [index,viewerLabel] of layer1.participant_labels.entries()){const report=buildPersonalPayload(layer1,viewerLabel);validatePersonalPayload(report);const html=await reportDocument(report);const fileId=`${id}-${index+1}`;await writeFile(join(dataDir,'reports',`${fileId}.html`),html,'utf8');reports.push({viewerLabel,report,reportUrl:`/reports/${fileId}.html`});}return send(res,200,{id,reports});}if(req.method==='POST'&&req.url==='/api/mentor'){return send(res,200,await mentor(await body(req)));}if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});const reportMatch=req.url.split('?')[0].match(/^\/reports\/([a-zA-Z0-9-]+)\.html$/);if(reportMatch){const file=join(dataDir,'reports',`${reportMatch[1]}.html`);if(!existsSync(file))return send(res,404,'Report not found','text/plain');return send(res,200,await readFile(file),'text/html');}let path=req.url==='/'?'/index.html':req.url.split('?')[0];path=normalize(path).replace(/^([.][.][\\/])+/, '');const file=join(root,path);if(!file.startsWith(root)||!existsSync(file))return send(res,404,'Not found','text/plain');const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.md':'text/markdown'};return send(res,200,await readFile(file),types[extname(file)]||'application/octet-stream');}catch(error){return send(res,500,{error:error.message||'Unexpected server error'});}});
server.listen(process.env.PORT||3000,()=>console.log('Bettersaid running at http://localhost:3000'));
